# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75acd492d28ef11369c18a2b714dcbfffa82e4120edeb01e08025c232d55de13ae75e60ecb652a2e34c40d0045d58294f80787a6c8a194280a6dd03a51828223

test:
  secret_key_base: 750024f19e43e66c0baa431b0f6ebd7cd8ccdad08c1a5616a448446b0fc0cb03cbd6473efc644ec3388c5389558d8141633a20326039cb367d51a433cf49e988

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
